# Generated by Django 2.2.16 on 2022-01-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220124_2109'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='inique_follow',
        ),
    ]
